### ISSUE TITLE
Error: Cannot find module 'prettier'

### ISSUE THREAD

**Issue by vvs-kim** [vvs-kim/gas_price#1]
- vscode 에서 prettier 적용 안됨
- yarn berry 의 패키지와 vscode 의 호환 문제로 보임
- Error: Cannot find module 'prettier' from '/Users/my_name/test/gas_price'
	at Function.e.exports [as sync] (/Users/my_name/.vscode/extensions/esbenp.prettier-vscode-9.9.0/dist/extension.js:1:37102)
	at t.ModuleResolver.findPkg (/Users/my_name/.vscode/extensions/esbenp.prettier-vscode-9.9.0/dist/extension.js:1:7353)
	at t.ModuleResolver.getPrettierInstance (/Users/my_name/.vscode/extensions/esbenp.prettier-vscode-9.9.0/dist/extension.js:1:3313)

**Comment by vvs-kim** [comment]
- yarn dlx @yarnpkg/sdks vscode
- 패키지 설치 후 yarn 과 vscode 가 호환하도록 명령어 작성해야 하는 것으로 보임
